# Generated by Django 5.1.8 on 2025-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('name_parameter', models.CharField(max_length=255)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('generation_granularity', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('name_file_json', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
