# Generated by Django 5.1.8 on 2025-05-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalparameter',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='clinicalparameter',
            name='generation_granularity',
        ),
        migrations.RemoveField(
            model_name='clinicalparameter',
            name='name_file_json',
        ),
        migrations.AlterField(
            model_name='clinicalparameter',
            name='parameter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinicalparameter',
            name='units',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='clinical.clinicalparameter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='clinical.patient')),
            ],
        ),
    ]
