# Generated by Django 5.1.8 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_remove_clinicalparameter_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_study',
            field=models.DateField(blank=True, null=True),
        ),
    ]
